name: Run Build

on:
  push:
    branches: [ "main" ]
    paths:
      - build/**
      - include/**
      - build.zig
      - build.zig.zon

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout
      uses: actions/checkout@v4

    - name: (Z) Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master

    - name: ▶️ Validate Build
      shell: bash
      run: zig build
